"""create users and assessments tables

Revision ID: dfadb23ef33c
Revises: 
Create Date: 2026-09-25 16:05:38.110781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfadb23ef33c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sa.Integer(), nullable=False),
    sa.Column('cp', sa.Integer(), nullable=False),
    sa.Column('trestbps', sa.Integer(), nullable=False),
    sa.Column('chol', sa.Integer(), nullable=False),
    sa.Column('fbs', sa.Integer(), nullable=False),
    sa.Column('restecg', sa.Integer(), nullable=False),
    sa.Column('thalach', sa.Integer(), nullable=False),
    sa.Column('exang', sa.Integer(), nullable=False),
    sa.Column('oldpeak', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('slope', sa.Integer(), nullable=False),
    sa.Column('ca', sa.Integer(), nullable=False),
    sa.Column('thal', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('predicted_disease', sa.Boolean(), nullable=False),
    sa.Column('disease_probability', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('selected_model', sa.String(length=64), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessments'))
    )
    op.create_index(op.f('ix_assessments_age'), 'assessments', ['age'], unique=False)
    op.create_index('ix_assessments_created_at', 'assessments', ['created_at'], unique=False)
    op.create_index('ix_assessments_model_version', 'assessments', ['model_version'], unique=False)
    op.create_index('ix_assessments_predicted_disease', 'assessments', ['predicted_disease'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_assessments_predicted_disease', table_name='assessments')
    op.drop_index('ix_assessments_model_version', table_name='assessments')
    op.drop_index('ix_assessments_created_at', table_name='assessments')
    op.drop_index(op.f('ix_assessments_age'), table_name='assessments')
    op.drop_table('assessments')
    # ### end Alembic commands ###
