"""FHIR code systems, profiles, and metadata (Phase 8).

This module holds the *vocabulary* the mapper uses so the mapping rules live
in one auditable place. It contains NO business logic and NO data access —
only constants describing how Remedy-AI's existing fields map onto standard
LOINC codes and UCUM units.
"""

from __future__ import annotations

from datetime import UTC, datetime

# --------------------------------------------------------------------------- #
# Provenance / meta
# --------------------------------------------------------------------------- #

GENERATOR = "Remedy-AI"
GENERATOR_VERSION = "2.0.0"
#: The tag stamped on every generated resource so downstream systems can tell
#: this output apart from a real EHR export.
GENERATED_TAG = (
    "Generated by Remedy-AI from this application's own assessment data. "
    "Educational prototype output — NOT a diagnosis and NOT a clinically "
    "validated measurement."
)
FHIR_VERSION = "4.0.1"

#: Canonical value for `meta.source` in generated resources.
META_SOURCE = f"urn:remedy-ai:{GENERATOR.lower()}"


def meta_tag(last_updated: str | None = None) -> dict[str, object]:
    """`meta` block stamped on every generated resource."""
    return {
        "versionId": "1",
        "lastUpdated": last_updated,
        "source": META_SOURCE,
        "profile": [f"urn:remedy-ai:profile:{GENERATOR.lower()}"],
        "tag": [
            {
                "system": META_SOURCE,
                "code": "generated",
                "display": GENERATED_TAG,
            }
        ],
    }


# --------------------------------------------------------------------------- #
# Code systems
# --------------------------------------------------------------------------- #

LOINC = "http://loinc.org"
UCUM = "http://unitsofmeasure.org"
LOCAL_ASSESSMENT = "urn:remedy-ai:codesystem:assessment"


#: The 13 ML input features → FHIR Observation codes/units. Features that map
#: to a real clinical measurement carry a UCUM unit; purely model-input
#: encodings (cp, slope, ca, thal) use the same code but no unit, and the
#: mapper labels them explicitly as model categories.
#: Each entry: (code system, code, display, UCUM unit, UCUM unit code).
FEATURE_OBSERVATION_MAP: dict[str, tuple[str, str, str, str, str]] = {
    "age": (LOINC, "424619002", "Age", "a", "a"),
    "sex": (LOINC, "184115007", "Administrative sex", "", ""),
    "cp": (LOINC, "2935-1", "Chest pain type (assessment category)", "", ""),
    "trestbps": (LOINC, "8480-6", "Systolic blood pressure", "mm[Hg]", "mm[Hg]"),
    "chol": (LOINC, "2093-3", "Cholesterol, total", "mg/dL", "mg/dL"),
    "fbs": (LOINC, "2339-0", "Fasting blood glucose elevated", "", ""),
    "restecg": (LOINC, "11524-6", "Resting ECG result", "", ""),
    "thalach": (LOINC, "8867-4", "Heart rate, maximal", "/min", "/min"),
    "exang": (LOINC, "2935-0", "Exercise induced angina", "", ""),
    "oldpeak": (LOINC, "59868-9", "ST depression, exercise induced", "mm", "mm"),
    "slope": (LOINC, "10230-1", "ST segment slope (assessment category)", "", ""),
    "ca": (LOINC, "11155-7", "Major vessels (assessment category)", "", ""),
    "thal": (LOINC, "33848-4", "Thalassemia indicator (assessment category)", "", ""),
}

#: Features whose value is an encoding, not a physical measurement.
CATEGORICAL_FEATURES = ("sex", "cp", "fbs", "restecg", "exang", "slope", "ca", "thal")

#: Category coding for the generated Observations / DiagnosticReport.
ASSESSMENT_CATEGORY_CODING = {
    "system": LOCAL_ASSESSMENT,
    "code": "cardiovascular-risk-assessment",
    "display": "Cardiovascular risk assessment (Remedy-AI)",
}

DIAGNOSTIC_REPORT_CODE = {
    "system": LOINC,
    "code": "11502-2",  # LOINC "Laboratory report"
    "display": "Cardiovascular risk assessment report",
}



def categorical_display(feature: str, value: int) -> str:
    """Human-readable display for the categorical assessment encodings.

    These are the model's *encodings*; the wording says so explicitly so a
    downstream system is never misled into thinking this is a clinical
    measurement vocabulary.
    """
    value = int(value)
    if feature == "cp":
        return {
            0: "Typical angina (model category 0)",
            1: "Atypical angina (model category 1)",
            2: "Non-anginal pain (model category 2)",
            3: "Asymptomatic (model category 3)",
        }.get(value, f"Unknown category ({value})")
    if feature == "restecg":
        return {
            0: "Normal (model category 0)",
            1: "ST-T wave abnormality (model category 1)",
            2: "Left ventricular hypertrophy probable/definite (model category 2)",
        }.get(value, f"Unknown category ({value})")
    if feature == "slope":
        return {
            0: "Upsloping (model category 0)",
            1: "Flat (model category 1)",
            2: "Downsloping (model category 2)",
        }.get(value, f"Unknown category ({value})")
    if feature == "ca":
        return f"{value} major vessel(s) (model category {value})"
    if feature == "thal":
        return {
            0: "Unknown/normal (model category 0)",
            1: "Fixed defect (model category 1)",
            2: "Reversible defect (model category 2)",
            3: "Other abnormality (model category 3)",
        }.get(value, f"Unknown category ({value})")
    if feature in ("sex", "fbs", "exang"):
        return {0: "No", 1: "Yes"}.get(value, f"Unknown ({value})")
    return str(value)


__all__ = [
    "GENERATOR",
    "GENERATOR_VERSION",
    "GENERATED_TAG",
    "FHIR_VERSION",
    "META_SOURCE",
    "meta_tag",
    "LOINC",
    "UCUM",
    "LOCAL_ASSESSMENT",
    "FEATURE_OBSERVATION_MAP",
    "CATEGORICAL_FEATURES",
    "ASSESSMENT_CATEGORY_CODING",
    "DIAGNOSTIC_REPORT_CODE",
    "categorical_display",
]


def bundle_timestamp() -> str:
    """Current UTC time as a FHIR `instant`/`dateTime` string."""
    return datetime.now(UTC).isoformat()
